## Rule Refinement Template Notebook:

In this notebook, it is assumed that data has been mined from twitter and is present in a JSON format, in a local file.

This notebook will separate all tweets by tag, and then run sub-section analysis on each of the tag dataframes.

Users must manually look through the tweets (sadly), and classify what "good" and "bad" tweets are. 

Using simple data tidying, and intuitive methods (set difference between tokenized strings of "good and bad" tweets), we attempt to provide information to the user to properly refine their rules, and evaluate recent adjustments to their rules.

In [1]:
#Load our custom library. Ouputs files in local directory automatically.
from mods.dfprocess import *
pd.set_option('display.max_rows', 500)

['Sept10_rule1-4.twts', 'sept9_rule1-4.twts', 'users.csv', 'rule1-4_trial3.twts', 'ProposedRules.txt', 'ruletest2.twts', 'runSept5_rule1-4.twts', 'rule1-4_pubmetrics2.twts', 'selectedtweets.json', 'Sept16_rule1-6.twts', 'parensrules.twts', 'sept11_rule1-4.twts', 'rule1-4_pubmetrics.twts', 'sept12_rule1-4.twts', 'mergedfile_rule1-6.twts', 'selectedTweets.json', 'Sept14_rule1-6.twts', 'rules3-4_trial2.twts', 'rules1-4_trial1.twts']

In [2]:
tweetDF = generatedataframe("./data/mergedfile_rule1-6.twts",5000)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4623 entries, 0 to 4622
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   tweetid        4623 non-null   int64
 1   text           4623 non-null   object
 2   created_at     4623 non-null   object
 3   tagid          4623 non-null   int64
 4   tag            4623 non-null   object
 5   userid         4623 non-null   int64
 6   username       4623 non-null   object
 7   rtcount        4623 non-null   int16
 8   repcount       4623 non-null   int16
 9   likecount      4623 non-null   int16
 10  qtcount        4623 non-null   int16
 11  tweet_type     4623 non-null   object
 12  ref_tweetid    4623 non-null   int64
 13  ref_authorid   4623 non-null   int64
 14  ref_rtcount    4623 non-null   int16
 15  ref_repcount   4623 non-null   int16
 16  ref_likecount  4623 non-null   int16
 17  ref_qtcount    4623 non-null   int16
dtypes: int16(8), int64(5), object(5)
memory usage: 433.5+ KB

In [3]:
tweetDF = cleanDF(tweetDF)
tweetDF.drop_duplicates(subset=["text"],inplace=True)
tweetDF = tweetDF[tweetDF['text'].astype(bool)]

In [4]:
#Get tags with: (dF.tag.unique()).tolist()
saiDF = getTagDF("SocietalShift", "./data/selectedtweets.json",tweetDF)

In [18]:
#Now set your good tweets. Look through the outputted file manually.
goodTweets = [16,0,1,9,12,18,30]

In [19]:
#The main part of the show.
gDict = {}
bDict = {}
gSet = set()
bSet = set()

hold = setdiffprocess(saiDF,goodTweets,gSet,gDict,bSet,bDict)

In [20]:
#Set operations
goodWords = gSet.difference(bSet)
badWords = bSet.difference(gSet)
intWords = gSet.intersection(bSet)

In [21]:
#Display Top Words
disp_topwords(badWords,bDict,50)

                 word  count
178          paradigm     13
245             shift      9
190              love      9
56               from      7
198              your      5
43             public      4
20               have      4
83               they      4
227             world      4
118              will      3
37             hidden      3
65               it’s      3
153              down      3
71       participants      2
33               said      2
129           turning      2
38               last      2
248          although      2
67             cannot      2
197              even      2
225           imagine      2
47            tonight      2
49               all.      2
116             could      2
242             lame.      2
58              can’t      2
176              also      2
223             place      2
14       pornography.      2
166              porn      2
210           special      2
150           needing      2
85             people      2
148            shift.      2
162             whole      2
163            \n\nif      2
144  satisfaction,,,,      2
272             doors      2
208             needs      2
16             black.      2
112            boldly      2
167             don’t      2
22        consequence      2
78            country      2
195         abduction      1
211             over,      1
193             think      1
192              none      1
204           rewards      1
194             stand      1

In [22]:
#Display Top Bad Words
disp_topwords(goodWords,gDict,50)

                        word  count
15               individuals      3
114                 survival      2
51             understanding      2
93                   friends      2
95                      mode      2
99                     screw      2
46                    you’re      2
102                 function      2
71                   utility      2
67                     music      1
62                   perhaps      1
82                     kills      1
81                    shift'      1
80                    friend      1
79                      very      1
78                     actor      1
77                   clichés      1
76                zeitgeist?      1
61              formalities,      1
75                   pulling      1
74                      crap      1
68                   odyssey      1
73   function:\n1.represents      1
72               preoccupied      1
63                    kween?      1
84                   society      1
64                  explicit      1
65                     we’re      1
66                  captured      1
70                  question      1
69                      term      1
83                    modern      1
87      (sometimes)\n\ncause      1
85                  circles.      1
86                    points      1
113                  \n2.use      1
112                    seems      1
111                   thomas      1
110                 becoming      1
109                 everyone      1
108                     race      1
107                     then      1
106                    know,      1
105                'paradigm      1
104                eachother      1
103                  coining      1
101                     damn      1
100                    brain      1
98                     vent,      1
97                  odysseus      1

In [23]:
disp_topwords(intWords,bDict,50)

          word  count
3        norms      5
22      social      5
2         just      4
6         need      4
10        when      4
16        that      4
4         into      3
20        this      3
14       about      2
13        like      2
19       where      2
18        what      2
1   judgements      2
27       value      2
8        would      2
5         most      2
12       great      1
15   something      1
11       there      1
17     feeling      1
9      because      1
7    zeitgeist      1
21    absolute      1
23       takes      1
24   political      1
25       shake      1
26       don't      1
0         talk      1

**Conclusion:** To be fair, we got 7/30 banger tweets from this rule. I am going to leave it alone! Finalized!